package vv.pms;

public enum Program {
    COMPUTER_SYSTEMS_ENGINEERING,
    SOFTWARE_ENGINEERING,
    ELECTRICAL_ENGINEERING,
    CIVIL_ENGINEERING,
    MECHANICAL_ENGINEERING,
    BIOMEDICAL_ENGINEERING,
    GENERAL_ENGINEERING
}
